"""Write the slide-to-notebook coverage map for a module.

    python3 tools/build_slide_map.py

Reads every notebook in the module's `notebooks/` folder, pulls the slide
references out of the section headings, and writes `slide-map.md` beside them.

The convention that makes this work: every section heading that covers deck
material carries its slide numbers, like

    ## 6. Data structures  *(slide 14)*
    ## 8. Charts  *(slides 26, 30)*

Slides with no interactive counterpart are listed in LECTURE_ONLY below, with
the reason. Anything in neither place is reported as an uncovered slide, which
is the point of the file: when a new deck arrives, this says what is missing.
"""
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MODULE = REPO / "modules" / "01a-programming-fundamentals"
NOTEBOOKS = MODULE / "notebooks"
OUTPUT = MODULE / "slide-map.md"

DECK = "Module_1_Part_1.pdf"
DECK_SLIDES = 58

LECTURE_ONLY = {
    1: "Title slide",
    2: "Agenda",
    3: "Section divider: Python Fundamentals",
    16: "Section divider: Python Environments and Libraries",
    36: "Section divider: Software Engineering Best Practices",
    48: "Questions",
    49: "Section divider: Appendices",
}

COVERED_ELSEWHERE = {
    50: "resources/git-hands-on.md",
    51: "resources/git-hands-on.md",
    52: "resources/git-hands-on.md",
    53: "resources/git-hands-on.md",
    54: "resources/git-hands-on.md",
    55: "resources/git-hands-on.md",
    56: "resources/git-hands-on.md",
    57: "resources/git-hands-on.md",
    58: "resources/git-hands-on.md",
}

HEADING = re.compile(
    r"^#{2,3}\s+(.*?)\s*\*\(slides?\s+([0-9,\s]+(?:(?:to|-)\s*\d+)?)\)\*\s*$",
    re.MULTILINE)


def slide_numbers(reference):
    """Expand a heading's slide reference into individual numbers.

    Accepts "14", "26, 30", "4 to 8" and "4-8".
    """
    reference = reference.strip()
    span = re.fullmatch(r"(\d+)\s*(?:to|-)\s*(\d+)", reference)
    if span:
        first, last = int(span.group(1)), int(span.group(2))
        return list(range(first, last + 1))
    return [int(n) for n in re.findall(r"\d+", reference)]


def scan():
    """Return {slide number: [(notebook name, heading text), ...]}."""
    found = {}
    for path in sorted(NOTEBOOKS.glob("*.ipynb")):
        notebook = json.loads(path.read_text())
        for cell in notebook["cells"]:
            if cell["cell_type"] != "markdown":
                continue
            for heading, numbers in HEADING.findall("".join(cell["source"])):
                for number in slide_numbers(numbers):
                    found.setdefault(number, []).append(
                        (path.name, heading.strip()))
    return found


def build():
    found = scan()
    covered = set(found) | set(LECTURE_ONLY) | set(COVERED_ELSEWHERE)
    missing = [n for n in range(1, DECK_SLIDES + 1) if n not in covered]

    lines = [
        "# Slide map",
        "",
        "Which part of `{}` each notebook covers. Generated by".format(DECK),
        "`tools/build_slide_map.py`; edit the notebooks, not this file.",
        "",
        "The deck has {} slides. {} have an interactive counterpart, {} are "
        "lecture-only,".format(DECK_SLIDES, len(found), len(LECTURE_ONLY)),
        "and {} are covered outside the notebooks.".format(
            len(COVERED_ELSEWHERE)),
        "",
        "| Slide | Covered by | Section |",
        "|---|---|---|",
    ]

    for number in range(1, DECK_SLIDES + 1):
        if number in found:
            for name, heading in found[number]:
                lines.append("| {} | `{}` | {} |".format(number, name, heading))
        elif number in LECTURE_ONLY:
            lines.append("| {} | not interactive | {} |".format(
                number, LECTURE_ONLY[number]))
        elif number in COVERED_ELSEWHERE:
            lines.append("| {} | `{}` | walkthrough, not a notebook |".format(
                number, COVERED_ELSEWHERE[number]))
        else:
            lines.append("| {} | **nothing** | **gap** |".format(number))

    lines += ["", "## Uncovered slides", ""]
    lines.append("None." if not missing
                 else "Slides {}. These need a section, or a line in "
                      "LECTURE_ONLY.".format(
                          ", ".join(str(n) for n in missing)))
    lines.append("")

    OUTPUT.write_text("\n".join(lines))
    print("wrote {} ({} slides mapped, {} lecture-only, {} elsewhere, "
          "{} uncovered)".format(OUTPUT.name, len(found), len(LECTURE_ONLY),
                                 len(COVERED_ELSEWHERE), len(missing)))
    if missing:
        print("  uncovered:", ", ".join(str(n) for n in missing))


if __name__ == "__main__":
    build()
